### ISSUE TITLE
ConnectionError when fetching device data

### ISSUE THREAD

**Issue by kipriyanov-aa** [cityairllc/cityair_python_api#4]
when requesting a large amount of data with `get_device_data` I get an error message that is not very helpful
```
ConnectionError: HTTPSConnectionPool(host='cityair.io', port=443): 
Max retries exceeded with url: /backend-api/request-v2.php?map=/DevicesApi2/GetPackets 
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f27b1ff4c90>:
Failed to establish a new connection: [Errno -2] Name or service not known'))
```
Exception handling is needed around `requests.post` 

To reproduce, try fetching more than three months of device data in one request.

**Comment by e-kor** [comment]
latest updated fixed the issue
in future, please provide more detailed description 

(turn on debug logging and provide full request body)
