### ISSUE TITLE
using reversed() on views breaks compatibility with Python 3 versions before 3.8

### ISSUE THREAD

**Issue by d1mach** [cityairllc/cityair_python_api#5]
Commit f1053b0641cdab83462a49d2b1ec0521c5a1cad5 introduced a call to `reversed()` applied to `dict_items` view produced by `value_types.items()`. This is only supported in Python 3.8 (explained in details here: https://stackoverflow.com/a/58413347/1328439).

Using `reversed(list(value_types.items()))` seems compatible with any version.

**Comment by e-kor** [comment]
fixed

https://pypi.org/project/cityair-api/0.2.65/
